server:
  port : 8080
#数据库设置
spring:
 datasource:
  driver-class-name : com.mysql.jdbc.Driver
  url : jdbc:mysql://localhost:3306/smile
  username : root
  password : root
  type : com.alibaba.druid.pool.DruidDataSource
  initialSize : 5
  maxActive : 20
  maxWait : 60000
  #每60秒运行一次空闲连接回收器
  timeBetweenEvictionRunsMillis : 60000
  #池中的连接空闲30分钟后被回收 
  minEvictableIdleTimeMillis : 1800000
  #验证使用的SQL语句  
  validationQuery : SELECT 1 FROM DUAL
 #数据库版本管理
 flyway:
  enabled: true
  # 禁止清理数据库表
  clean-disabled: true
  # 如果数据库不是空表，需要设置成 true，否则启动报错
  baseline-on-migrate: true
  # 与 baseline-on-migrate: true 搭配使用
  baseline-version: 0
 #html模板
 thymeleaf:
  prefix=classpath:/templates/
  cache = false
 #redis
 redis:
  database : 0
  host : localhost
  port : 6379
  password : 123456
  jedis.pool.max-active : 8
  jedis.pool.max-wait : -1
  jedis.pool.max-idle : 8
  jedis.pool.min-idle : 0
  timeout : 0

#mybatis location
mybatis-plus:
 mapper-locations : classpath*:/mapper/**Mapper.xml
 type-aliases-package : com.smile.operation.**

