server:
  port: 8080
test:
  name: xuyongqiang
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smileant?useUnicode=true&characterEncoding=utf8&mysqlEncoding=utf8
    # url : jdbc:mysql://192.168.1.94:4002/smile?useUnicode=true&characterEncoding=utf8&mysqlEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    enabled: true
    clean-disabled: true
    baseline-on-migrate: true
    baseline-version: 0
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 'PROCEED2017'
    jedis.pool.max-active: 8
    jedis.pool.max-wait: -1
    jedis.pool.max-idle: 8
    jedis.pool.min-idle: 0
    timeout: 5000
  jpa:
    show-sql: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.smile.operation.**
